### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jeremiahlukus**
development no longer works, it is now beta

### CODE REVIEW

**Comment by andrewhavens** [comment]
@jeremiahlukus How did you discover this change? I have been using development without any issues. What changed in your environment?

**Comment by jeremiahlukus** [comment]
This is the first time using it when you use development it gives a nice error saying you have to use `beta`

**Comment by jeremiahlukus** [comment]
```
Don't know how to build task 'archive:development' (see --tasks)
Did you mean?  archive:beta
```

**Comment by andrewhavens** [comment]
The rake task for building the `.ipa` file is not the same as the certificate type. I'm not even sure `rake archive:beta` is valid anymore. When building for beta testing through TestFlight, you will use a distribution certificate, and when developing for local development, you will use a development certificate (simply `rake archive`). I'm going to roll back this change to the readme, because the type of certificate is still `:development`, not `:beta`. This will fix #33.

**Pull request merged**
